List<String> allExerciseList = [
  'Bar Dip',
  'Bench Press (barbell)',
  'Bench Press (dumbbell)',
  'Bench Press (machine)',
  'Chest Press (cable)',
  'Decline Chest Press (cable)',
  'Incline Chest Press (cable)',
  'Decline Bench Press (barbell)',
  'Decline Bench Press (dumbbell)',
  'Decline Bench Press (machine)',
  'Incline Bench Press (barbell)',
  'Incline Bench Press (dumbbell)',
  'Incline Bench Press (machine)',
  'Chest Fly (barbell)',
  'Chest Fly (dumbbell)',
  'Incline Chest Fly (barbell)',
  'Incline Chest Fly (dumbbell)',
  'Decline Chest Fly (barbell)',
  'Decline Chest Fly (dumbbell)',
  'Incline Push-Up',
  'Push-Up',
  'Decline Push-Up',
  'Kettlebell Floor Press',
  'Kneeling Incline Push-Up',
  'Kneeling Push-Up',
  'Machine Chest Fly',
  'Butterfly',
  'Pec Deck',
  'Push-Up Against Wall',
  'Push-Ups With Feet in Rings',
  'Front Raise (barbell)',
  'Front Raise (dumbbell)',
  'Rear Delt Row (barbell)',
  'Rear Delt Row (dumbbell)',
  'Rear Delt Row (cable)',
  'Upright Row (barbell)',
  'Upright Row (cable)',
  'Lateral Raise (dumbbell)',
  'Lateral Raise (barbell)',
  'Lateral Raise (machine)',
  'Shoulder Press (dumbbell)',
  'Shoulder Press (barbell)',
  'Shoulder Press (machine)',
  'Face Pull',
  'Overhead Press (dumbbell)'
      'Overhead Press (barbell)',
  'Overhead Press (machine)',
  'Reverse Flyes (cable)',
  'Reverse Flyes (dumbbell)',
  'Reverse Flyes (barbell)',
  'Reverse Flyes (machine)',
  'Bicep Curl (dumbbell)',
  'Bicep Curl (barbell)',
  'Bicep Curl (cable)',
  'Bicep Curl (machine)',
  'Preacher Curl (barbell)',
  'Preacher Curl (dumbbell)',
  'Preacher Curl (cable)',
  'Hammer Curl',
  'Concentration Curl',
  'Incline bicep Curl',
  'Spider Curl',
  'Triceps Extension (barbell)',
  'Triceps Extension (dumbbell)',
  'Bench Dip',
  'Close Grip PushUp',
  'Triceps Pushdown (bar)',
  'Triceps Pushdown (rope)',
  'Squat',
  'Hack Squat',
  'Barbell Lunge',
  'Leg Curl',
  'Box Squat',
  'Leg Press',
  'Bulgarian Split Squat',
  'Chin Up',
  'Pull Up',
  'Back Extension',
  'Muscle Up',
  'Row (barbell)',
  'Shrug (barbell)',
  'Shrug (dumbbell)',
  'Cable Row',
  'Chin Up',
  'Clean',
  'Clean and Jerk',
  'Deadlift',
  'Dumbbell Row',
  'Lat Pulldown (Wide Grip)',
  'Lat Pulldown (Close Grip)',
  'Lat Pulldown (Behind)',
  'Muscle-Up (Bar)',
  'Muscle-Up (Rings)',
  'One-Handed Cable Row',
  'One-Handed Lat Pulldown',
  'Pull-Up',
  'Sumo Deadlift',
  'T Bar Row',
  'Romanian Deadlift',
  'Glute Bridge',
  'Hip Thrust',
  'Hip Thrust Machine',
  'Cable Crunches',
  'Crunches',
  'Hanging Knee Raise',
  'Hanging Leg Raise',
  'Hanging Sit Up',
  'Wood Chop',
  'Plank',
  'Sit Up',
  'Calf Raise',
  'Seated Calf Raise',
  'Standing Calf Raise',
  'Wrist Curl (barbell)',
  'Wrist Curl (dumbbell)',
  'Farmers Walk'
];
